name: Prepare for Deployment

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # The type of machine to run the job on.

    steps:
    - uses: actions/checkout@v2 # This checks out your repository.

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # This will use the latest version of Python 3.

    - name: Install dependencies
      run: pip3 install beautifulsoup4 requests jinja2

    - name: Run scrape_site.py
      run: python scrape_site.py

    - name: Run generate_site.py
      run: python generate_site.py

    - name: Add index.html and textures.json to git
      run: |
          git add index.html
          git add textures.json
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Generate site

